name: todoapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.7
  flex_color_scheme: ^8.3.0
  font_awesome_flutter: ^10.10.0
  gap: ^3.0.1
  go_router: ^16.2.1
  google_fonts: ^6.3.1
  intl: ^0.20.2
  path: ^1.9.1
  sqflite: ^2.4.2
  flutter_riverpod: ^3.0.0
  # flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
